<?php
require_once __DIR__.'/helpers.php';
$id=(int)($_GET['campaign']??$_POST['campaign_id']??0);$stmt=db()->prepare(campaign_query('c.id=?'));$stmt->execute([$id]);$campaign=$stmt->fetch();if(!$campaign){http_response_code(404);exit('Kampanye tidak ditemukan.');}
$pageTitle='Donasi untuk '.$campaign['title'];$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 $name=trim($_POST['donor_name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$amount=(float)preg_replace('/[^0-9]/','',$_POST['amount']??'0');$anonymous=isset($_POST['anonymous'])?1:0;$message=trim($_POST['message']??'');$payment=trim($_POST['payment_method']??'');
 if($name==='')$errors[]='Nama wajib diisi.'; if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='Email tidak valid.'; if($amount<10000)$errors[]='Minimum donasi Rp10.000.'; if($payment==='')$errors[]='Pilih metode pembayaran.';
 try{$proof=upload_file('proof_file','proofs',['image/jpeg','image/png','image/webp','application/pdf'],true);}catch(Throwable $e){$errors[]=$e->getMessage();$proof=null;}
 if(!$errors){$code=receipt_code();$stmt=db()->prepare('INSERT INTO donations(campaign_id,user_id,donor_name,email,phone,amount,anonymous,message,payment_method,proof_file,status,receipt_code) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$id,user()['id']??null,$name,$email,$phone,$amount,$anonymous,$message,$payment,$proof,'pending',$code]);flash('success','Donasi berhasil dikirim dan menunggu verifikasi admin.');redirect('donation-success.php?code='.urlencode($code));}
}
include __DIR__.'/partials/header.php';
?>
<section class="form-page container"><div class="glass form-card"><div class="form-heading"><span class="eyebrow">Form donasi</span><h1>Salurkan kebaikan Anda</h1><p><?=e($campaign['title'])?></p></div><?php if($errors):?><div class="alert error"><strong>Periksa kembali:</strong><ul><?php foreach($errors as $er):?><li><?=e($er)?></li><?php endforeach;?></ul></div><?php endif;?><form method="post" enctype="multipart/form-data" class="form-grid" data-donation-form><?=csrf_field()?><input type="hidden" name="campaign_id" value="<?=$id?>"><label class="full">Nominal donasi<div class="amount-input"><span>Rp</span><input name="amount" inputmode="numeric" placeholder="100.000" value="<?=old('amount')?>" required data-currency></div></label><div class="quick-amounts full"><button type="button" data-amount="50000">Rp50 rb</button><button type="button" data-amount="100000">Rp100 rb</button><button type="button" data-amount="250000">Rp250 rb</button><button type="button" data-amount="500000">Rp500 rb</button></div><label>Nama lengkap<input name="donor_name" value="<?=old('donor_name',user()['name']??'')?>" required></label><label>Email<input type="email" name="email" value="<?=old('email',user()['email']??'')?>" required></label><label>Nomor WhatsApp<input name="phone" value="<?=old('phone')?>" placeholder="08xxxxxxxxxx"></label><label>Metode pembayaran<select name="payment_method" required><option value="">Pilih metode</option><option>Bank BCA</option><option>Bank Mandiri</option><option>Bank BRI</option><option>QRIS</option></select></label><label class="full">Bukti transfer<input type="file" name="proof_file" accept=".jpg,.jpeg,.png,.webp,.pdf" required><small>JPG, PNG, WEBP, atau PDF. Maksimal 3 MB.</small></label><label class="full">Pesan dukungan<textarea name="message" rows="3" placeholder="Tulis doa atau pesan..."><?=old('message')?></textarea></label><label class="check full"><input type="checkbox" name="anonymous" <?=isset($_POST['anonymous'])?'checked':''?>><span>Sembunyikan nama saya dari halaman publik</span></label><div class="transfer-info full glass-subtle"><strong>Informasi pembayaran demo</strong><p>BCA 1234567890 a.n. Yayasan PeduliKita atau pindai QRIS pada aplikasi pembayaran Anda.</p></div><button class="btn primary wide full" type="submit">Kirim Donasi</button></form></div><aside class="glass form-summary"><div class="detail-cover compact category-<?=e(strtolower($campaign['category']))?>"><span><?=category_icon($campaign['category'])?></span></div><h3><?=e($campaign['title'])?></h3><div class="progress"><span style="width:<?=campaign_progress($campaign)?>%"></span></div><p><?=money((float)$campaign['raised'])?> terkumpul dari <?=money((float)$campaign['target_amount'])?></p></aside></section>
<?php include __DIR__.'/partials/footer.php'; ?>
