<?php
require_once __DIR__.'/helpers.php';$pageTitle='Dashboard Transparansi';
$summary=db()->query("SELECT (SELECT COALESCE(SUM(amount),0) FROM donations WHERE status='verified') received,(SELECT COALESCE(SUM(amount),0) FROM fund_usages) used,(SELECT COUNT(*) FROM campaigns WHERE status='active') active_campaigns,(SELECT COUNT(*) FROM donations WHERE status='verified') donors")->fetch();
$rows=db()->query(campaign_query("c.status IN ('active','completed')")." ORDER BY raised DESC")->fetchAll();
$usage=db()->query("SELECT f.*,c.title campaign_title FROM fund_usages f JOIN campaigns c ON c.id=f.campaign_id ORDER BY f.usage_date DESC LIMIT 10")->fetchAll();
include __DIR__.'/partials/header.php';?>
<section class="page-hero container"><span class="eyebrow">Dashboard transparansi</span><h1>Setiap rupiah dapat dipantau</h1><p>Ringkasan dana masuk, penggunaan dana, dan perkembangan kampanye yang diperbarui oleh pengelola.</p></section>
<section class="container section top-tight"><div class="metric-grid"><div class="metric glass"><span>Dana terverifikasi</span><strong><?=money((float)$summary['received'])?></strong><small>Total donasi yang telah dikonfirmasi</small></div><div class="metric glass"><span>Dana digunakan</span><strong><?=money((float)$summary['used'])?></strong><small>Tercatat dalam laporan penggunaan</small></div><div class="metric glass"><span>Saldo program</span><strong><?=money((float)$summary['received']-(float)$summary['used'])?></strong><small>Dana tersedia untuk penyaluran</small></div><div class="metric glass"><span>Transaksi terverifikasi</span><strong><?=number_format((int)$summary['donors'])?></strong><small>Kontribusi yang telah diterima</small></div></div>
<div class="glass panel"><div class="section-head"><div><span class="eyebrow">Kinerja kampanye</span><h2>Perolehan terhadap target</h2></div></div><div class="transparency-list"><?php foreach($rows as $r):?><div><div class="trans-title"><strong><?=e($r['title'])?></strong><span><?=number_format(campaign_progress($r),0)?>%</span></div><div class="progress"><span style="width:<?=campaign_progress($r)?>%"></span></div><small><?=money((float)$r['raised'])?> dari <?=money((float)$r['target_amount'])?> · <?=number_format((int)$r['donor_count'])?> donatur</small></div><?php endforeach;?></div></div>
<div class="glass panel"><div class="section-head"><div><span class="eyebrow">Penggunaan terbaru</span><h2>Realisasi dana</h2></div><a class="btn ghost small" href="<?=url('export-transparency.php')?>">Unduh CSV</a></div><div class="data-table"><table><thead><tr><th>Tanggal</th><th>Kampanye</th><th>Penggunaan</th><th>Nominal</th></tr></thead><tbody><?php foreach($usage as $u):?><tr><td><?=date('d/m/Y',strtotime($u['usage_date']))?></td><td><?=e($u['campaign_title'])?></td><td><strong><?=e($u['title'])?></strong><small><?=e($u['description'])?></small></td><td><?=money((float)$u['amount'])?></td></tr><?php endforeach;?></tbody></table></div></div></section>
<?php include __DIR__.'/partials/footer.php'; ?>
